/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vaultSol from "./Vault.sol";
export { CXPTToken__factory } from "./CXPTToken__factory";
export { SynthERC20__factory } from "./SynthERC20__factory";
export { SynthFactory__factory } from "./SynthFactory__factory";
