/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AdvertisementTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CxmputeAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "CxmputeSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "EmbeddingsProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "LLMProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MediaProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MetadataTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MoonProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NetworkStatsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProviderTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProvisionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ScrapingProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ServiceMetadataTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TTSProvisionPoolTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}