import { SceneConfig } from '../types/scene';

export const heroPresets: Record<string, SceneConfig> = {
  morphingSpheres: {
    name: 'Morphing Spheres',
    description: 'Dynamic spheres with transmission materials and physics simulation',
    camera: {
      position: [0, 0, 15],
      fov: 17.5,
      near: 1,
      far: 20,
      enableDamping: true,
      dampingFactor: 0.05,
    },
    environment: {
      type: 'color',
      background: '#141622',
      intensity: 1,
    },
    objects: [
      {
        type: 'sphere',
        position: [0, 0, 0],
        scale: 1,
        material: {
          type: 'transmission',
          color: '#4060ff',
          transmission: 0.9,
          thickness: 0.1,
          roughness: 0.1,
          clearcoat: 1,
          clearcoatRoughness: 0.1,
          ior: 1.5,
        },
        physics: {
          type: 'dynamic',
          mass: 1,
          friction: 0.1,
        },
        castShadow: true,
        receiveShadow: true,
      },
      {
        type: 'sphere',
        position: [3, 2, -1],
        scale: 0.8,
        material: {
          type: 'transmission',
          color: '#20ffa0',
          transmission: 0.8,
          thickness: 0.2,
          roughness: 0.2,
          metalness: 0.1,
        },
        physics: {
          type: 'dynamic',
          mass: 0.8,
        },
        castShadow: true,
      },
      {
        type: 'sphere',
        position: [-2, -1, 2],
        scale: 1.2,
        material: {
          type: 'transmission',
          color: '#ff4060',
          transmission: 0.7,
          thickness: 0.3,
          roughness: 0.3,
        },
        physics: {
          type: 'dynamic',
          mass: 1.2,
        },
        castShadow: true,
      },
    ],
    lights: [
      {
        type: 'ambient',
        intensity: 0.4,
        color: '#ffffff',
      },
      {
        type: 'spot',
        position: [10, 10, 10],
        angle: 0.15,
        penumbra: 1,
        intensity: 1,
        castShadow: true,
        shadow: {
          mapSize: [2048, 2048],
        },
      },
      {
        type: 'point',
        position: [4, 4, 4],
        intensity: 4,
        distance: 2.5,
        color: '#4060ff',
      },
      {
        type: 'point',
        position: [-4, -4, -4],
        intensity: 4,
        distance: 2.5,
        color: '#20ffa0',
      },
    ],
    postProcessing: {
      bloom: {
        enabled: true,
        intensity: 0.9,
        threshold: 0.1,
        radius: 0.8,
        mipmapBlur: true,
      },
      ssao: {
        enabled: true,
        intensity: 4,
        radius: 1,
        bias: 0.5,
      },
    },
  },

  floatingIslands: {
    name: 'Floating Islands',
    description: 'Levitating geometric forms with dynamic lighting and atmosphere',
    camera: {
      position: [0, 5, 12],
      target: [0, 0, 0],
      fov: 60,
      autoRotate: true,
      autoRotateSpeed: 0.5,
      enableDamping: true,
    },
    environment: {
      type: 'gradient',
      background: ['#0a0a2a', '#1a1a3a', '#2a2a4a'],
      fog: {
        color: '#1a1a3a',
        near: 5,
        far: 25,
        density: 0.05,
      },
    },
    objects: [
      {
        type: 'octahedron',
        position: [0, 3, 0],
        scale: 2,
        material: {
          type: 'physical',
          color: '#7FDBFF',
          metalness: 0.8,
          roughness: 0.2,
          clearcoat: 1,
          clearcoatRoughness: 0.1,
          emissive: '#001a33',
          emissiveIntensity: 0.3,
        },
        wave: {
          type: 'sine',
          amplitude: 0.2,
          frequency: 0.5,
          speed: 0.8,
        },
        castShadow: true,
      },
      {
        type: 'icosahedron',
        position: [-4, 1, -2],
        scale: 1.5,
        material: {
          type: 'glass',
          color: '#ff6b6b',
          transmission: 0.9,
          thickness: 0.5,
          roughness: 0,
        },
        noise: {
          type: 'perlin',
          scale: 1.5,
          speed: 0.3,
          amplitude: 0.1,
          octaves: 3,
        },
        castShadow: true,
      },
      {
        type: 'dodecahedron',
        position: [4, -1, 3],
        scale: 1.8,
        material: {
          type: 'holographic',
          color: '#4ecdc4',
          opacity: 0.8,
          emissive: '#001a1a',
          emissiveIntensity: 0.2,
        },
        wave: {
          type: 'circular',
          amplitude: 0.15,
          frequency: 1,
          speed: 0.6,
        },
      },
      {
        type: 'plane',
        position: [0, -3, 0],
        scale: [20, 1, 20],
        material: {
          type: 'physical',
          color: '#2c3e50',
          metalness: 0.1,
          roughness: 0.8,
          opacity: 0.7,
          transparent: true,
        },
        receiveShadow: true,
      },
    ],
    lights: [
      {
        type: 'ambient',
        intensity: 0.2,
        color: '#404080',
      },
      {
        type: 'directional',
        position: [10, 10, 5],
        intensity: 1,
        color: '#ffffff',
        castShadow: true,
        shadow: {
          mapSize: [2048, 2048],
          camera: {
            near: 0.1,
            far: 50,
            left: -10,
            right: 10,
            top: 10,
            bottom: -10,
          },
        },
      },
      {
        type: 'point',
        position: [0, 8, 0],
        intensity: 2,
        color: '#7FDBFF',
        distance: 15,
      },
    ],
    particles: [
      {
        type: 'dust',
        count: 1000,
        color: ['#7FDBFF', '#ff6b6b', '#4ecdc4'],
        size: 0.02,
        speed: 0.1,
        opacity: 0.6,
        turbulence: 0.5,
      },
    ],
    postProcessing: {
      bloom: {
        enabled: true,
        intensity: 1.2,
        threshold: 0.1,
        radius: 0.9,
      },
      dof: {
        enabled: true,
        focusDistance: 12,
        focalLength: 0.02,
        bokehScale: 3,
      },
      vignette: {
        enabled: true,
        darkness: 0.3,
        offset: 0.2,
      },
    },
  },

  crystalCavern: {
    name: 'Crystal Cavern',
    description: 'Luminous crystals in a mystical underground environment',
    camera: {
      position: [0, 3, 8],
      target: [0, 1, 0],
      fov: 65,
      enableDamping: true,
      dampingFactor: 0.08,
    },
    environment: {
      type: 'gradient',
      background: ['#0d0015', '#1a0033', '#2d004d'],
      fog: {
        color: '#1a0033',
        near: 2,
        far: 20,
      },
    },
    objects: [
      // Ground
      {
        type: 'plane',
        position: [0, 0, 0],
        rotation: [-Math.PI / 2, 0, 0],
        scale: [15, 15, 1],
        material: {
          type: 'physical',
          color: '#1a1a2e',
          metalness: 0.3,
          roughness: 0.7,
          emissive: '#0f0f23',
          emissiveIntensity: 0.1,
        },
        receiveShadow: true,
      },
      // Central large crystal
      {
        type: 'octahedron',
        position: [0, 2, 0],
        scale: [1, 3, 1],
        material: {
          type: 'glass',
          color: '#9d4edd',
          transmission: 0.95,
          thickness: 0.2,
          roughness: 0,
          ior: 2.4,
        },
        wave: {
          type: 'sine',
          amplitude: 0.05,
          frequency: 1.5,
          speed: 0.4,
        },
        castShadow: true,
      },
      // Surrounding crystals
      {
        type: 'tetrahedron',
        position: [-3, 1, -2],
        scale: 1.5,
        material: {
          type: 'glass',
          color: '#c77dff',
          transmission: 0.9,
          thickness: 0.3,
          roughness: 0.1,
        },
        noise: {
          type: 'perlin',
          scale: 2,
          speed: 0.2,
          amplitude: 0.05,
        },
        castShadow: true,
      },
      {
        type: 'octahedron',
        position: [3, 0.8, 1],
        scale: 1.2,
        material: {
          type: 'glass',
          color: '#7209b7',
          transmission: 0.85,
          thickness: 0.4,
          roughness: 0.05,
        },
        wave: {
          type: 'ripple',
          amplitude: 0.1,
          frequency: 2,
          speed: 0.6,
        },
        castShadow: true,
      },
      {
        type: 'icosahedron',
        position: [0, 0.5, -4],
        scale: 0.8,
        material: {
          type: 'glass',
          color: '#f72585',
          transmission: 0.8,
          thickness: 0.5,
          roughness: 0.2,
        },
        castShadow: true,
      },
    ],
    lights: [
      {
        type: 'ambient',
        intensity: 0.15,
        color: '#4a148c',
      },
      {
        type: 'point',
        position: [0, 4, 0],
        intensity: 3,
        color: '#9d4edd',
        distance: 8,
        castShadow: true,
      },
      {
        type: 'point',
        position: [-3, 2, -2],
        intensity: 2,
        color: '#c77dff',
        distance: 5,
      },
      {
        type: 'point',
        position: [3, 2, 1],
        intensity: 2,
        color: '#7209b7',
        distance: 5,
      },
      {
        type: 'spot',
        position: [0, 8, 0],
        target: [0, 0, 0],
        angle: 0.3,
        penumbra: 0.5,
        intensity: 1.5,
        color: '#ffffff',
        castShadow: true,
      },
    ],
    particles: [
      {
        type: 'fireflies',
        count: 150,
        color: ['#9d4edd', '#c77dff', '#f72585'],
        size: 0.03,
        speed: 0.15,
        opacity: 0.8,
        trail: true,
        trailLength: 8,
      },
    ],
    postProcessing: {
      bloom: {
        enabled: true,
        intensity: 1.8,
        threshold: 0.05,
        radius: 1.2,
        mipmapBlur: true,
      },
      chromaticAberration: {
        enabled: true,
        offset: [0.001, 0.001],
      },
      film: {
        enabled: true,
        noiseIntensity: 0.05,
        scanlineIntensity: 0.02,
        scanlineCount: 1024,
      },
    },
  },

  techShowcase: {
    name: 'Tech Showcase',
    description: 'Sleek technological display with holographic elements',
    camera: {
      position: [5, 3, 8],
      target: [0, 1, 0],
      fov: 50,
      enableDamping: true,
      dampingFactor: 0.1,
      autoRotate: true,
      autoRotateSpeed: 0.3,
    },
    environment: {
      type: 'gradient',
      background: ['#0a0a0a', '#1a1a1a'],
      fog: {
        color: '#0a0a0a',
        near: 1,
        far: 30,
      },
    },
    objects: [
      // Base platform
      {
        type: 'cylinder',
        position: [0, 0, 0],
        scale: [4, 0.1, 4],
        material: {
          type: 'physical',
          color: '#2c3e50',
          metalness: 0.9,
          roughness: 0.1,
          emissive: '#0066cc',
          emissiveIntensity: 0.1,
        },
        receiveShadow: true,
      },
      // Central torus
      {
        type: 'torus',
        position: [0, 2, 0],
        scale: 1.5,
        material: {
          type: 'holographic',
          color: '#00ffff',
          opacity: 0.7,
          transmission: 0.3,
        },
        wave: {
          type: 'sine',
          amplitude: 0.1,
          frequency: 2,
          speed: 1,
        },
      },
      // Floating spheres
      {
        type: 'sphere',
        position: [0, 3.5, 0],
        scale: 0.3,
        material: {
          type: 'physical',
          color: '#ffffff',
          metalness: 1,
          roughness: 0,
          emissive: '#00ffff',
          emissiveIntensity: 0.5,
        },
        followMouse: true,
        followMouseSpeed: 0.08,
        followMouseDistance: 3,
        castShadow: true,
      },
      // Ring elements
      {
        type: 'ring',
        position: [0, 1, 0],
        scale: 3,
        material: {
          type: 'transmission',
          color: '#0099ff',
          transmission: 0.8,
          thickness: 0.1,
          opacity: 0.8,
          transparent: true,
        },
        wave: {
          type: 'circular',
          amplitude: 0.05,
          frequency: 3,
          speed: 1.5,
        },
      },
    ],
    lights: [
      {
        type: 'ambient',
        intensity: 0.2,
        color: '#004080',
      },
      {
        type: 'rect',
        position: [0, 6, 0],
        width: 6,
        height: 6,
        color: '#00ffff',
        intensity: 0.8,
      },
      {
        type: 'spot',
        position: [5, 5, 5],
        target: [0, 1, 0],
        angle: 0.2,
        penumbra: 0.3,
        intensity: 2,
        color: '#ffffff',
        castShadow: true,
      },
      {
        type: 'point',
        position: [0, 4, 0],
        intensity: 1,
        color: '#00ffff',
        distance: 8,
      },
    ],
    particles: [
      {
        type: 'fireflies',
        count: 80,
        color: '#00ffff',
        size: 0.04,
        speed: 0.2,
        opacity: 0.6,
        trail: false,
      },
    ],
    postProcessing: {
      bloom: {
        enabled: true,
        intensity: 1.5,
        threshold: 0.1,
        radius: 0.8,
      },
      outline: {
        enabled: true,
        thickness: 1.5,
        color: '#00ffff',
      },
      film: {
        enabled: true,
        noiseIntensity: 0.08,
        scanlineIntensity: 0.05,
        scanlineCount: 2048,
      },
    },
  },

  organicFlow: {
    name: 'Organic Flow',
    description: 'Fluid, organic shapes with natural movements and soft lighting',
    camera: {
      position: [0, 4, 10],
      target: [0, 0, 0],
      fov: 60,
      autoRotate: true,
      autoRotateSpeed: 0.2,
      enableDamping: true,
    },
    environment: {
      type: 'gradient',
      background: ['#f7f1e8', '#e8dcc6', '#d4c5a9'],
    },
    objects: [
      // Main organic form
      {
        type: 'sphere',
        position: [0, 1, 0],
        scale: 2.5,
        material: {
          type: 'physical',
          color: '#f4a261',
          metalness: 0.1,
          roughness: 0.3,
          clearcoat: 0.8,
          clearcoatRoughness: 0.2,
          transmission: 0.1,
          thickness: 0.5,
        },
        noise: {
          type: 'perlin',
          scale: 1.2,
          speed: 0.15,
          amplitude: 0.3,
          octaves: 4,
          persistence: 0.6,
          lacunarity: 2.0,
        },
        castShadow: true,
      },
      // Smaller flowing elements
      {
        type: 'sphere',
        position: [-2, 2, 1],
        scale: 1.2,
        material: {
          type: 'physical',
          color: '#e76f51',
          metalness: 0.2,
          roughness: 0.4,
          clearcoat: 0.6,
        },
        wave: {
          type: 'ripple',
          amplitude: 0.2,
          frequency: 0.8,
          speed: 0.3,
        },
        castShadow: true,
      },
      {
        type: 'sphere',
        position: [2.5, 0.5, -1],
        scale: 0.8,
        material: {
          type: 'physical',
          color: '#2a9d8f',
          metalness: 0.3,
          roughness: 0.2,
          clearcoat: 0.9,
          transmission: 0.2,
        },
        noise: {
          type: 'curl',
          scale: 2,
          speed: 0.2,
          amplitude: 0.15,
        },
        castShadow: true,
      },
      // Ground plane
      {
        type: 'plane',
        position: [0, -1, 0],
        rotation: [-Math.PI / 2, 0, 0],
        scale: [20, 20, 1],
        material: {
          type: 'lambert',
          color: '#f7f1e8',
          opacity: 0.8,
          transparent: true,
        },
        receiveShadow: true,
      },
    ],
    lights: [
      {
        type: 'ambient',
        intensity: 0.6,
        color: '#fff8e7',
      },
      {
        type: 'directional',
        position: [5, 8, 3],
        intensity: 0.8,
        color: '#fff8e7',
        castShadow: true,
        shadow: {
          mapSize: [2048, 2048],
          camera: {
            near: 0.1,
            far: 50,
            left: -10,
            right: 10,
            top: 10,
            bottom: -10,
          },
        },
      },
      {
        type: 'hemisphere',
        position: [0, 0, 0],
        intensity: 0.4,
        color: '#87ceeb',
      },
    ],
    postProcessing: {
      bloom: {
        enabled: true,
        intensity: 0.6,
        threshold: 0.8,
        radius: 1,
      },
      vignette: {
        enabled: true,
        darkness: 0.2,
        offset: 0.1,
      },
      tonemap: {
        enabled: true,
        exposure: 1.2,
        whitePoint: 1.0,
      },
    },
  },
}; 