/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultSol from "./Vault.sol";
export type { vaultSol };
export type { CXPTToken } from "./CXPTToken";
export type { SynthERC20 } from "./SynthERC20";
export type { SynthFactory } from "./SynthFactory";
