import Button from "@/components/button/button";
import styles from "./101.module.css";
import Link from "next/link";

export default function Home() {
    return (
        <main className={styles.main}>
            <div className={styles.docWrapper}>
                <h1>Cxmpute 101: What is Cxmpute?</h1>
                <p>Before we dive into Cxmpute 101, let&apos;s start with an analogy to understand idle compute power. Imagine your computer as a power plant with extra capacity sitting idle most of the time. Cxmpute is like a digital power grid that taps into that unused energy and turns it into valuable compute power for everyone. And don&apos;t worry—your personal data stays secure while your machine contributes to a global network.</p>
                <h2>What Is Cxmpute?</h2>
                <em>Cxmpute rewards you for sharing your idle compute resources.</em>
                <p>At Cxmpute, our mission is to create a network where everyone wins. Whether you need powerful compute resources or have idle cycles to spare, Cxmpute makes it simple for you to participate. Turn your underused computer into a revenue-generating asset while developers and enterprises gain access to scalable, cost-effective compute power.</p>
                <p>Getting started is easy—a few clicks, and your device joins a secure, decentralized network. You remain in full control, choosing exactly when to share your resources without any impact on your personal data or system performance.</p>
                <h2>How does it work?</h2>
                <p>Cxmpute connects those who need extra compute power with providers who have it. When a developer, company, or researcher requires additional processing capacity, the network automatically matches their request with available resources. This seamless system powers a range of applications, from AI model inference and data analysis to serverless computing.</p>
                <p>Cxmpute offers several key services:</p>
                <ul>
                    <li><strong>LLM Inference:</strong> Access dozens of popular language models for text generation, conversation, and reasoning tasks.</li>
                    <li><strong>Text Embeddings:</strong> Generate vector embeddings for semantic search, RAG applications, and similarity matching.</li>
                    <li><strong>Text-to-Speech:</strong> Convert text to natural-sounding speech with various voice options.</li>
                    <li><strong>Web Scraping:</strong> Extract and process content from web pages with intelligent content extraction.</li>
                    <li><strong>Tool Use & JSON Mode:</strong> Enable structured outputs and function calling for advanced AI applications.</li>
                </ul>
                <h2>Why Is Cxmpute a Game-Changer?</h2>
                <h3>For Providers</h3>
                <p>Earn rewards by monetizing your idle compute cycles. Whether you&apos;re an individual or run a professional data center, you decide when and how to participate, and you&apos;re directly compensated for your contributions.</p>
                <h3>For Users</h3>
                <p>Access powerful, flexible computing resources without being tied to a centralized cloud provider. Enjoy cost-effective, scalable solutions that empower innovation and democratize access to high-performance compute power.</p>
                <h2>Why Didn&apos;t a Solution Like Cxmpute Exist Sooner?</h2>
                <p>Three key factors: technology, vision, and market demand. Traditional systems rely on massive centralized data centers, leaving little room for individual participation. With advances in decentralized protocols and blockchain, Cxmpute is ushering in a new era—one that puts control and rewards directly into the hands of everyday users.</p>
                <p>Additionally, the explosive growth of Large Language Models (LLMs) has created unprecedented demand for AI inference capabilities. LLMs have become increasingly popular across industries, from customer service chatbots to content generation and code assistance. This surge in demand represents a perfect use case for distributed inference, where the computational load can be efficiently spread across a network of providers rather than requiring massive centralized infrastructure.</p>
                <p>By harnessing the untapped potential of idle compute power and addressing the growing need for accessible AI services, Cxmpute is reshaping the computing economy. The benefits generated by sharing your resources are returned directly to you, fostering a more equitable and innovative future.</p>
                <Link href='/'>
                    <Button text="Back to Home" backgroundColor={'#20a191'} />
                </Link>
            </div>
        </main>
    );
}