/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISynthERC20__factory } from "./ISynthERC20__factory";
export { Vault__factory } from "./Vault__factory";
